# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.png"
    high_res_favicon: "/img/favicon.png"
    apple_touch_icon: "/img/favicon.png"
    keywords:
    site_verification:
        google:
        baidu:

    # Enable generate structured-data as JSON+LD for SEO or not.
    #        Set as 'false' if it cause some wrong when `hexo g`.
    structured_data: true

# Jump Links Settings
url:
    rss:
    daily_pic: "#"
    logo: "#"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "I write many code to write less code. üíª"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#29d"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: false

# Reading experience
reading:
    entry_excerpt: 80

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F5F5F5"
    #bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:

# Images Settings
img:
    logo: "/img/logo.png"
    avatar: "/img/avatar.png"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    random_thumbnail: "/img/random/material-"
    footer_image:
        #upyun_logo:
            #link: "https://www.upyun.com/"
            #src: "/img/upyun_logo.svg"

# Custom Fonts
#   family: the font-family which will be used in the theme
#   host: uri of fonts host.
#       Available value of "host": google | baomitu | ustc | custom
fonts:
    family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "ÂæÆËΩØÈõÖÈªë", Arial, sans-serif
    use: google
    custom_font_host:

# Card Elevation Level
card_elevation: 2

# Copyright
# Specify the date when the site was setup.
#   For example, if you set it as 2015, then footer will show '¬© 2015 - 2017'
copyright_since: 2016

# Qrcode for redirect at other device
#   use: choose which method to generate the qrcode for each posts.
#       Available value of "use": plugin | online
#           - When use "plugin", you need to install the hexo-helper-qrcode.
#           - When use "online", the qrcode will be generated by 'pan.baidu.com' in China.
qrcode:
    enable: false
    use: plugin


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# Code highlight
# You can only enable one of them to avoid issues.
# Also you need to disable highlight option in hexo's _config.yml.
#
#    Prettify
#        theme: # Available value in /source/css/prettify/[theme].min.css
prettify:
    enable: false
    theme: "github-v2"

#    Hanabi (https://github.com/egoist/hanabi)
#        line_number: [true/false] # Show line number for code block
#        includeDefaultColors: [true/false] # Use default hanabi colors
#        customColors: This value accept a string or am array to setting for hanabi colors.
#                    - If `includeDefaultColors` is true, this will append colors to the color pool
#                    - If `includeDefaultColors` is false, this will instead default color pool
hanabi:
    enable: false
    line_number: true
    includeDefaultColors: true
    customColors: 

# Post License
# You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
#   For example, you can setup a CC license as:
#       'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'
# You can also use Front-Matter `license` to override this setting.
license: 

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# TOC Button

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: true

# SNS Menu
sns:
    email: gua@desgard.com
    facebook: "https://www.facebook.com/facebook"
    twitter: "https://twitter.com/twitter"
    googleplus: "https://www.google.com/"
    weibo:
    instagram:
    tumblr:
    github:
    linkedin:
    zhihu:
    bilibili:
    telegram:

# SNS Share Switch
sns_share:
    twitter: true
    facebook: false
    googleplus: false
    weibo: true
    linkedin: false
    qq: false
    telegram: false

# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "mailto:gua@desgard.com"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
        #About:
            #link: "/about"
            #icon: person
            #divider: false
    article_num:
        use: false
        divider: false
    footer:
        divider: true
        theme: true
        support: false
        feedback: false
        material: false


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# MaterialCDN
# When you set 'use' as true, the needed css, js, font file will have a new src.
# The new src will have the base domain you configured in 'base'.
materialcdn: 
    use: 
    base: 

# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | livere | gitment | gitalk | valine
# If you want to use gitment or gitalk,you should get the client_id and client_secret form https://github.com/settings/applications/new
# If you want to use valine,you should get the app_id and app_key form https://leancloud.cn ,more setting please see https://valine.js.org
comment:
    use: 
    shortname: # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    livere_data_uid:
    gitment_repo:   # git repo of the hexo
    gitment_owner:  # git repo's owner
    gitment_client_id:  # github app client id 
    gitment_client_secret :  # github app client secret 
    valine_leancloud_appId:  # leancloud application app id
    valine_leancloud_appKey:  # leancloud application app key
    valine_notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
    valine_verify: false # valine verify code (true/false)
    valine_pageSize: 10 # comment list page size
    valine_avatar: identicon # gravatar style https://valine.js.org/#/avatar
    valine_lang: zh-cn # i18n
    valine_placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
    valine_guest_info: nick,mail,link #valine comment header info
    gitalk_repo: # git repo of the hexo
    gitalk_owner: # git repo's owner
    gitalk_client_id: # github app client id 
    gitalk_client_secret: # github app client secret

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key:

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
    google_site_id:
    baidu_site_id: c5a8123bc51782a3083a631ed9ff50e4
    cnzz_site_id:

# Leancloud Views
leancloud:
    enable: false
    app_id: #‰Ω†ÁöÑ app_id
    app_key: #‰Ω†ÁöÑ app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi ‰∏çËíúÂ≠ê Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

vendors:
# MaterialCDN
#   You can load theme unique files from your private cdn or oss.
#   The new src will have the base domain you configured below.
#   For example
    # MathJax 2.7.0-2.7.1
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js"
#   materialcdn: https://cdn.jsdelivr.net/npm/hexo-material@1.4.0/source
    materialcdn:
    # jQuery 2.2.0
    jquery:
    # nprogress 0.2.0
    nprogress:
    # FontAwesome 4.5.0
    fontawesome:
    # Prettify r298 (only prettify.js)
    prettify:
    # Material Icons 3.0.1
    material_icons:

Front-matter:
    mathjax: true